model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 16
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 70001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 16
      resolution: 32
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.2

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    wrap: True
    num_workers: 10
    train:
      target: ldm.data.custom_2.PersonalizeTrain0
      params:
        csv_path_train: ./data/train.txt
        size: 32
        degradation: pil_nearest
        flip_p: 0.5

    validation:
      target: ldm.data.custom_2.PersonalizeVal0
      params:
        csv_path_val: ./data/test.txt
        size: 32
        degradation: pil_nearest

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 4000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    max_epochs: 2500
    accumulate_grad_batches: 2
